[package]
name = "capnpc-abstract"
version = "0.1.0"
authors = ["mohaque"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.10.1"

[build-dependencies]
capnpc = "0.10.1"
